### ISSUE TITLE
Running container does not work

### ISSUE THREAD

**Issue by yueguoguo** [flaviobarros/shiny-wordcloud#11]
Hi 

I am trying to replicate your demo. I cloned the source files into my own machine, and ran `docker build -t word-cloud` to create an image.

Then I tried to run the image with `docker run -it --rm -p 80:80 word-cloud` but got the error `"exec:\"/usr/bin/shiny-server.sh\":permission denied"`

I then used `CMD["chmod", "+x", "/usr/bin/shiny-server.sh"]` instead of `CMD["/usr/bin/shiny-server.sh"]` and this time no error popped up, nothing happened afterwards - the app was not running. 

If I pull your image from Docker Hub and did the same everything worked fine! 

Do you have any idea about why this might happen? Thanks a lot!

**Comment by flaviobarros** [comment]
Not yet. I think this can happen because of the docker version.

**Comment by pjastam** [comment]
Hi Flavio,

I also did not manage to replicate your demo, but got it working after a small update of the [Dockerfile](https://github.com/flaviobarros/shiny-wordcloud/files/2058640/Dockerfile.txt). As you can see, I added lines 14 and 15 as libxml2 and libxml2-dev are needed for installation of the R package tm at line 24. Without these two extra lines of code, error messages appeared during installation time.

Anyhow, thanks for your Wordcloud example. I hope my suggestion may also help Zhang Le (yueguoguo) solving his issue (of ten months ago, yeah, I know).

**Comment by flaviobarros** [comment]
@pjastam can you submit a pull request?
