### ISSUE TITLE
Docker build fails on openssl install

### ISSUE THREAD

**Issue by victorklos** [flaviobarros/shiny-wordcloud#4]
The build fails with:

```
    http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl0.9.8_0.9.8o-4squeeze14_amd64.deb:
2016-05-23 15:09:04 ERROR 404: Not Found.
```

This error is fatal. The `wget` and `dpkg -i` combination seems somewhat error prone. Why is `openssl` required in exactly this version? Are you sure the normal repos are unsuitable?

**Comment by kissmygritts** [comment]
@victorklos You can delete the entire ssl line and instead include `libssl-dev` at the bottom of the first `RUN` command.

**Comment by victorklos** [comment]
thanks, that makes sense. will you incorporate this or shall I open a pull req?

**Comment by flaviobarros** [comment]
Merged pull request.
