### ISSUE TITLE
fork review

### ISSUE THREAD

**Issue by vnijs** [flaviobarros/shiny-wordcloud#8]
Not really an issue but ...

I forked your shiny-wordcloud repo to https://github.com/radiant-rstats/docker-radiant today. I adapted the Docker file and everything seems to work as intended locally. I also pushed the image to Docker Hub (vnijs/radiant). This is my first attempt at dockerizing so I'd be happy to hear any comments or suggestions you might have (e.g., is using RUN git clone ... in the Dockerfile a good idea?).

**Comment by flaviobarros** [comment]
Nice work. " is using RUN git clone ... in the Dockerfile a good idea?". I THINK that it's ok. If you make sure that the repo is ok. I'm testing your repo rigth now.

**Comment by vnijs** [comment]
I'm also wondering if using docker might be a nice way to distribute a shiny app to users to run locally. They just install docker and then pull the image. The main thing that would be needed would be something like a desktop icon that a user would double click to start-up the image and a stop button in the browser/app that would (1) stop the shiny app and (2) stop to docker image/deamon. Is something like that feasible do you think?

**Comment by flaviobarros** [comment]
Umm, I don't know. But are you aware of kitematic? I think this can be a easy solution.

**Comment by vnijs** [comment]
kitematic does look nice but starting up and shutting down the process doesn't look as easy as opening up Rstudio and using the addins menu. Thanks for the input. Will close this 'issue' for now.
